<?php

declare(strict_types=1);

namespace jkorn\pvpcore;

/**
 * Created by PhpStorm.
 * User: jkorn2324
 * Date: 2019-04-04
 * Time: 16:01
 */

use jkorn\pvpcore\commands\CommandRegistry;
use pocketmine\plugin\PluginBase;
use jkorn\pvpcore\WorldHandler;
use jkorn\pvpcore\PvPCoreListener;

class PvPCore extends PluginBase
{

    private static $instance;

    private static $worldHandler;

    public function onEnable()
    {
        parent::onEnable(); // TODO: Change the autogenerated stub
        self::$instance = $this;
        CommandRegistry::init();
        self::$worldHandler = new WorldHandler();
        self::getServer()->getPluginManager()->registerEvents(new PvPCoreListener($this), $this);
    }

    public static function getInstance() : PvPCore {
        return self::$instance;
    }

    public static function getWorldHandler() : WorldHandler {
        return self::$worldHandler;
    }

    public function onDisable()
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }

    public static function canParse(string $s, bool $isInteger) : bool {

        $canParse = true;

        if(is_string($s)) {
            $abc = "ABCDEFGHIJKLMNOPQRZTUVWXYZ";
            $invalid = $abc . strtoupper($abc) . "!@#$%^&*()_+={}[]|:;\"',<>?/";
            if ($isInteger) $invalid = $invalid . ".";
            for ($i = 0; $i < strlen($invalid); $i++) {
                $character = $invalid[$i] . "";
                if (strpos($s, $character) === true) {
                    $canParse = false;
                    break;
                }
            }
        } else if (is_float($s)){
            $canParse = true;
        } else if (is_int($s)){
            $canParse = true;
        } else {
            $canParse = false;
        }

        return $canParse;
    }

    public function onCommand(\pocketmine\command\CommandSender $sender, \pocketmine\command\Command $command, string $label, array $args): bool
    {
        return parent::onCommand($sender, $command, $label, $args); // TODO: Change the autogenerated stub
    }

}