<?php

declare(strict_types=1);

namespace jkorn\pvpcore;

/**
 * Created by PhpStorm.
 * User: jkorn2324
 * Date: 2019-04-04
 * Time: 16:01
 */

use jkorn\pvpcore\commands\AreaCommand;
use jkorn\pvpcore\commands\PvPCommand;
use jkorn\pvpcore\world\areas\AreaHandler;
use jkorn\pvpcore\world\areas\PvPCArea;
use jkorn\pvpcore\world\PvPCWorld;
use pocketmine\command\Command;
use pocketmine\command\CommandSender;
use pocketmine\event\EventPriority;
use pocketmine\plugin\PluginBase;
use jkorn\pvpcore\world\WorldHandler;
use pocketmine\Server;
use pocketmine\utils\Config;

class PvPCore extends PluginBase
{

    private static $instance;

    private static $worldHandler;

    private static $areaHandler;

    /**
     *
     */
    public function onEnable()
    {
        parent::onEnable();
        self::$instance = $this;
        $this->initCommands();
        $this->initConfig();
        self::$worldHandler = new WorldHandler($this);
        self::$areaHandler = new AreaHandler($this);
        self::getServer()->getPluginManager()->registerEvents(new PvPCoreListener($this), $this);
    }

    /**
     * @return PvPCore
     */
    public static function getInstance() : PvPCore {
        return self::$instance;
    }

    /**
     * @return WorldHandler
     */
    public static function getWorldHandler() : WorldHandler {
        return self::$worldHandler;
    }

    /**
     * @return AreaHandler
     */
    public static function getAreaHandler() : AreaHandler {
        return self::$areaHandler;
    }

    private function initConfig() : void {

        $levels = $this->getServer()->getLevels();

        $allWorlds = [];

        foreach($levels as $level) {
            $name = $level->getName();
            $defaultAttackDelay = 10;
            $customKb = false;
            $knockback = 0.4;
            $world = new PvPCWorld($name, $customKb, $defaultAttackDelay, $knockback);
            array_push($allWorlds, $world);
        }

        $file = $this->getDataFolder() . "/config.yml";
        $config = new Config($file, Config::YAML, []);

        $worldsKey = "worlds";
        $areasKey = "areas";

        if(!$config->exists($worldsKey)) {
            $config->set($worldsKey, []);
            $config->save();
        }

        if(!$config->exists($areasKey)) {
            $config->set($areasKey, []);
            $config->save();
        }

        $worlds = $config->get($worldsKey);

        $edited = false;

        foreach($allWorlds as $world) {
            if($world instanceof PvPCWorld) {
                $name = $world->getLevel()->getName();
                if(!array_key_exists($name, $worlds)) {
                    $worlds[$name] = $world->toMap();
                    $edited = true;
                }
            }
        }

        if($edited === true) {
            $config->set("$worldsKey", $worlds);
            $config->save();
        }
    }

    /**
     *
     */
    public function onDisable()
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $s
     * @param bool $isInteger
     * @return bool
     */
    public static function canParse($s, bool $isInteger) : bool {

        $canParse = true;

        if(is_string($s)) {
            $abc = "ABCDEFGHIJKLMNOPQRZTUVWXYZ";
            $invalid = $abc . strtoupper($abc) . "!@#$%^&*()_+={}[]|:;\"',<>?/";
            if ($isInteger) $invalid = $invalid . ".";
            for ($i = 0; $i < strlen($invalid); $i++) {
                $character = $invalid[$i] . "";
                if (strpos($s, $character) === true) {
                    $canParse = false;
                    break;
                }
            }
        } else {
            if($isInteger){
                $canParse = is_int($s);
            } else {
                $canParse = is_float($s);
            }
        }

        return $canParse;
    }

    /**
     * @param string $name
     * @param Command $command
     */
    public function registerCommand(string $name, Command $command){
        Server::getInstance()->getCommandMap()->register($name, $command);
    }

    /**
     *
     */
    private function initCommands(){
        $this->registerCommand("pvp", new PvPCommand());
        $this->registerCommand("pvparea", new AreaCommand());
    }

    /**
     * @param CommandSender $sender
     * @param Command $command
     * @param string $label
     * @param array $args
     * @return bool
     */
    public function onCommand(CommandSender $sender, Command $command, string $label, array $args): bool
    {
        return parent::onCommand($sender, $command, $label, $args); // TODO: Change the autogenerated stub
    }

}